[build]
  publish = "."
  command = "" # no build step

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Optional: SPA-style fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
